#Setup ~~~
#Follow these 3 steps to set up your site.

#Step 1: change mozillascience to the user name you chose on GitHub:
user: mozillascience

#Step 2: give your study group a name and a short description:
title: Our Study Group
description: "A study group."

#Step 3: press the green 'Commit Changes' button at the bottom of this page.

# That's it, your website is all set up!
# You can see it at http://YourUserName.github.io/studyGroup/
# No need to change anything below this line.
# To make your first event, check out the instructions at https://github.com/mozillascience/studyGroup#how-to-launch-a-new-event
# Having trouble? Open a new issue at https://github.com/mozillascience/studyGroup/issues and we'll help you out ASAP!



titleBackground: "https://s3-us-west-2.amazonaws.com/webmaker-kits/learning%402x.jpg"






# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/billdoesphysics
#   - title: github
#     url: https://github.com/BillMills/studyGroupTemplate

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
