#Setup ~~~
#Follow these 2 steps to set up your site.

#Step 1: give your study group a name and a short description:
title: University of Toronto Coders
description: "We are a group of students and researchers dedicated to learning about and sharing scientific coding techniques and knowledge in an effort to improve scientific research."

#Step 2: press the green 'Commit Changes' button at the bottom of this page.

# That's it, your website is all set up!
# You can see it at https://YourUserName.github.io/studyGroup/
# No need to change anything below this line.
# To make your first event, check out the instructions at https://github.com/mozillascience/studyGroup#how-to-launch-a-new-event
# Having trouble? Open a new issue at https://github.com/mozillascience/studyGroup/issues and we'll help you out ASAP!

# Optional Configuration
# None of these things need to be changed - but feel free!

titleBackground: "https://s3-us-west-2.amazonaws.com/webmaker-kits/learning%402x.jpg"
headlineSmall: "Welcome To The U of T Coders Group!"
headlineMain: "Let's Work Together"
avatar: "img/logos/logo_icon_dark.png"

# Setup Google Calendar
# Usage:
# 1. create a new google account; set the calendar to 'public'
# 2. change 'USER' in the example urls below to the username of the google account you made for your calendar
# 3. set calendar_on: True.

calendar_on: True
calendar_embed_url: "https://www.google.com/calendar/embed?src=utorontostudygroup@gmail.com"
calendar_ical_url: "https://www.google.com/calendar/ical/utorontostudygroup@gmail.com/public/basic.ics"

#========================================
# No touching anything below this line :)
#========================================
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
future: true
